### ISSUE TITLE
SoyBase DSCensor Error

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/DSCensor#4] opened 2024-04-12 18:43 UTC
Hello:

On the dev.soybase.org website (https://dev.soybase.org/resources/annotation_stats/) there is an error where the user can not choose a species of glycine for DSCensor.  I am not sure what is missing or wrong but there is no stats or BUSCOs on the page.

**Comment by adf-ncgr** [comment] 2024-04-12 18:48
Thanks @jd-campbell looks like the problem is on our end, affecting dscensor.legumeinfo.org (which this site has iframe'd) only with respect to annotation stats, not genome stats. @ctcncgr and I will try to sort it out ASAP!

**Comment by jd-campbell** [comment] 2024-04-12 18:53
@adf-ncgr & @ctcncgr 
thank you for looking in it. 
ASAP is not required- dev.soybase.org is not live yet.

**Comment by adf-ncgr** [comment] 2024-04-12 18:54
true, but dscensor.legumeinfo.org is live and has the same issue...

**Comment by ctcncgr** [comment] 2024-04-12 20:59
This should be fixed. Thanks for reporting the issue.

**Comment by adf-ncgr** [comment] 2024-04-12 21:34
thanks @ctcncgr !

**Comment by ctcncgr** [comment] 2024-04-15 17:04
I'm going to close this. Please reopen if the issue remains.

**Closed as completed by ctcncgr** 2024-04-15 17:04 UTC
Labels: bug
